services:
  postgres:
    container_name: postgres_db
    image: postgres:18.2
    environment:
      POSTGRES_USER: postgres_docker
      POSTGRES_PASSWORD: my_pass
      PGDATA: /data/postgres
    volumes:
      - ./postgres-data:/data/postgres
    ports:
      - "5433:5432"